learning_users/basicapp/urls.py
from operator import index
from django.shortcuts import render
from basicapp import views
from django.contrib import admin
from django.urls import path
from numpy import r_
from django.conf.urls import include

app_name = 'basicapp'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name = 'user_login')
]

learning_users/learning_users/urls.py
from operator import index
from basicapp import views
from django.contrib import admin
from django.urls import path,include
from numpy import r_
from django.conf.urls import include
from basicapp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = 'index'),
    path('basicapp/',include('basicapp.urls', namespace="basicapp")),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

learning_users/basicapp/models.py
from pickletools import read_unicodestring1
from statistics import mode
from typing_extensions import Self
from sqlalchemy import true
from django.db import models
from wsgiref.validate import validator
from django import forms
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

learning_users/basicapp/forms.py
from dataclasses import field
from wsgiref.validate import validator
import django
from django.core import validators
from django import forms
from basicapp.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')
        # fields = '__all__'

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basicapp/views.py
import imp
from pickletools import read_unicodestring1
from xml.etree.ElementInclude import include
from django import http
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
# FOR MTV
from basicapp.models import UserProfileInfo
from basicapp.forms import UserForm,UserProfileInfoForm
#FOR LOGIN
# from django import reverse

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.

def index(request):
    return render(request,'basicapp/index.html')

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user # Have a look at the models.py file, in that, the "user" is declared and has a one to one relation with the "User" model which is inbuilt in django, this means that one user can have only one profile

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basicapp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
@login_required # This line of code causes the function to be login required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    

@login_required
def special(request):
    return HttpResponse("You are logged in!")

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username') # "get" grabs by the name tag in the html page
        password = request.POST.get('password')

        user = authenticate(username = username,password = password) # built in authentication function

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account is not active!")
        else:
            print("Someone tried to login and failed!")
            print("Username{} and password{}".format(username,password))
            return HttpResponse("Invalid login details!")
    else:
        return render(request,'basicapp/login.html',{})

learning_users/templates/basicapp/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">    </head>
    <body>
        <nav class="navbar navbar-default navbar static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                    <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li> <a class="navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>

                    {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li> <!-- logout will refer to the link in the urls.py(project) file -->
                    {% else %}
                    <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>

        </nav>

        {% block body_block %}
        {% endblock %}
        <script src="" async defer></script>
    </body>
</html>

learning_users/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>DJANGO LEVEL FIVE</h1>
</div>
{% endblock %}

learning_users/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basicapp:user_login' %}" method="POST"> <!-- Will go to the urls.py file(app) to use the user_login function -->
        {% csrf_token %}
        <label for="username">Username : </label>
        <input type="text" name = "username" placeholder="Enter username">
        <label for="password">Password : </label>
        <input type="password" name = "password" placeholder="Enter password">
        <input type="submit" name="" value = "Login">
    </form>
</div>
{% endblock %}

learning_users/templates/basicapp/registration.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
{% if registered %} <!-- Here,'regitered is a key from a dictionary in the views.py file in the function which calls it' -->
<h1>Thank you for registering!</h1>
{% else %}
<h1>Register here</h1>
<h3>Fill out the form : </h3>
<form enctype="multipart/form-data" method = "post" action="">
    {% csrf_token %}
        {{ user_form.as_p }}<!-- the user_from and the profile_form are going to be mentioned in the dictionsry of the function of the views.py file -->
        {{ profile_form.as_p }}<!-- the user_from and the profile_form are going to be mentioned in the dictionsry of the function of the views.py file -->
    <input type="submit" name="" id="" value="Register">
</form>
{% endif %}    
{% endblock %}
</div>